name: untitled3
description: A new Flutter project.

publish_to: 'none' # Remove this line if you are publishing this package

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0  # Firebase core dependency
  firebase_auth: ^5.4.2  # Firebase authentication dependency
  cloud_firestore: ^5.6.3  # Firebase firestore dependency (필요에 따라 추가)
  firebase_storage: ^12.4.2
  firebase_analytics: ^11.4.2
  firebase_database: ^11.3.2
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  # 필요한 다른 Firebase 의존성도 추가 (예: firebase_messaging, firebase_database 등)


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true